### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by eriklysoe** [rikuu/Gap2Seq#14]
Hi

Should probably be

git clone --recursive https://github.com/rikuu/Gap2Seq
cd Gap2Seq
cd thirdparty/htslib 
make
cd ..
mkdir build
cd build
cmake ../..
make

Since CMakeLists.txt is in the main folder, and not in Gap2Seq/thirdparty

Cheers
Erik

**Comment by rikuu** [comment]
Yeah, that makes sense.
Fixed
