### ISSUE TITLE
error running

### ISSUE THREAD

**Issue by jarojasva** [rikuu/Gap2Seq#15]
Cut 71 scaffolds into 71 contigs and 0 gaps
Traceback (most recent call last):
  File "./Gap2Seq", line 445, in <module>
    args['bed'], args['gaps'] = cut_gaps(args['k'], args['fuz'], args['mask'], args['scaffolds'])
  File "./Gap2Seq", line 311, in cut_gaps
    return open(bed_file, 'r'), open(gap_file, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'tmp.gaps'

What should I do?

**Comment by jarojasva** [comment]
I run the test and the program was fine. Then, I tried to run it with my data, and this was the error after reading de -reads:

HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 0:
  #000: /mnt/c/Users/AsusLap/Documents/Otros/Apps/Gap2Seq/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5A.c line 407 in H5Aopen(): unable to load attribute info from object header for attribute: 'version'
    major: Attribute
    minor: Unable to initialize object
  #001: /mnt/c/Users/AsusLap/Documents/Otros/Apps/Gap2Seq/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Oattribute.c line 537 in H5O_attr_open_by_name(): can't locate attribute: 'version'
    major: Attribute
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 0:
  #000: /mnt/c/Users/AsusLap/Documents/Otros/Apps/Gap2Seq/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5A.c line 677 in H5Aget_space(): not an attribute
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 0:
  #000: /mnt/c/Users/AsusLap/Documents/Otros/Apps/Gap2Seq/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5S.c line 883 in H5Sget_simple_extent_dims(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 0:
  #000: /mnt/c/Users/AsusLap/Documents/Otros/Apps/Gap2Seq/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5A.c line 634 in H5Aread(): not an attribute
    major: Invalid arguments to routine
    minor: Inappropriate type
DBG building failed: Unable to open bank '/mnt/c/Users/AsusLap/Documents/UNAM/Genomas/116_181_Alcanivorax_GOM/RawDataIllumina_Alcanivorax/181_Fastqc/Muestra_1_DNA_Alcanivorax_S47_R1_001_1P.fastq' (if it is a list of files, perhaps some of the files inside don't exist)
Traceback (most recent call last):
  File "./Gap2Seq", line 497, in <module>
    fill_scaffolds(args['gaps'], args['filled'], args['k'], args['fuz'],
  File "./Gap2Seq", line 243, in fill_scaffolds
    subprocess.check_call(command)
  File "/home/jarv/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/mnt/c/Users/AsusLap/Documents/Otros/Apps/Gap2Seq/build/Gap2Seq-core', '-k', '31', '-fuz', '10', '-solid', '2', '-nb-cores', '1', '-dist-error', '500', '-max-mem', '20', '-randseed', '0', '-reads'

My read documents are 1,700,000 KB.

What do you recommend?

**Comment by ens-LCampbell** [comment]
@jarojasva Any chance you ever got any sort of reply regarding this error ? I have the exact same issue. Doesn't seem to be any support for this package anymore by the looks of it :(

**Comment by ammaraziz** [comment]
I think this is related to https://github.com/rikuu/Gap2Seq/issues/11 that is when no gaps are filled it returns an error due to a missing file.
