### ISSUE TITLE
tag a release

### ISSUE THREAD

**Issue by notestaff** [rikuu/Gap2Seq#2]
Can you tag the current release (3.0?), if it's stable?  This would help with creating a bioconda recipe for Gap2Seq.

**Comment by rikuu** [comment]
I finally got around to fixing some bugs and building on Mac OS, so I now tagged a release and will close this issue. If you need help with a bioconda recipe, just open a new issue.

**Comment by notestaff** [comment]
@rikuu great, thanks a lot!
