### ISSUE TITLE
Error running Gage Example

### ISSUE THREAD

**Issue by vrohnie** [rikuu/Gap2Seq#6]
So because I'm very new to this I tried to run the Gage example with the Example Data.

When running 

python3.4 /[mybuildFolderPath]/Gap2Seq --scaffolds Assembly/SGA/genome.scf.fasta --filled Assembly/SGA/genome.scf.fill.fasta --reads Data/original/frag_1.fastq,Data/original/frag_2.fastq,Data/original/shortjump_1.fastq,Data/original/shortjump_2.fastq

I get following Ouput:

Cutting gaps
Merging filled gaps and contigs
Traceback (most recent call last):
  File "/home/schusterbauer/Programs/Gap2Seq-3.1/build/Gap2Seq", line 505, in <module>
    merge_gaps(args['filled'], args['final_out'])
  File "/home/schusterbauer/Programs/Gap2Seq-3.1/build/Gap2Seq", line 319, in merge_gaps
    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/schusterbauer/Programs/Gap2Seq-3.1/build/GapMerger', '-scaffolds', 'Assembly/SGA/genome.scf.fill.fasta', '-gaps', 'tmp.filled', '-contigs', 'tmp.contigs']' returned non-zero exit status 1

As this didn't mean a lot to me, but I think I tracked it down to Gap2Seq-core failing to fill any gaps and therefore creating an empty 'Assembly/SGA/genome.scf.fill.fasta' and no 'tmp.filled' file.

But the real question now is, why doesn't Gap2Seq-core work properly. 

I ran it directly with:

/[mybuildFolderPath]/Gap2Seq-core -scaffolds Assembly/SGA/genome.scf.fasta -filled Assembly/SGA/genome.scf.fill.fasta -reads Data/original/frag_1.fastq,Data/original/frag_2.fastq,Data/original/shortjump_1.fastq,Data/original/shortjump_2.fastq

and it seems to do stuff but then in the end just outputs:

etc...
[Graph: build branching nodes            ]  97   %   elapsed:   0 min 1  sec   remaining:   0 min 0  s[Graph: build branching nodes            ]  98   %   elapsed:   0 min 1  sec   remaining:   0 min 0  s[Graph: build branching nodes            ]  99   %   elapsed:   0 min 1  sec   remaining:   0 min 0  s[Graph: build branching nodes            ]  100  %   elapsed:   0 min 1  sec   remaining:   0 min 0  s[Graph: nb branching found : 406997      ]  100  %   elapsed:   0 min 1  sec   remaining:   0 min 0  s[Graph: nb branching found : 406997      ]  100  %   elapsed:   0 min 1  sec   remaining:   0 min 0  sec   cpu: 719.6 %   mem: [ 700,  703,  770] MB 
Max mem: 2684354560
Filled 0 gaps out of 0

I would appreciate any help

Sidenote: Gap2Seq 2.1 seems to run smoothly, but I was mainly excited to try the Insertion Genotyping :/

Greetings,
Veronika

**Comment by rikuu** [comment]
I think I fixed the crash now. Thanks for reporting this!
Feel free to open more issues if you have any other trouble.

**Comment by vrohnie** [comment]
Thanks, It does run now :)

**Comment by MgLaMontagne** [comment]
I received the exact same error as above (see below) when I tried to run the same Gage example. I ran the Gap2Seq 3.1, which I installed through bioconda.  I have attached the package list from the conda environment.
Any help would be greatly appreciated.
Michael

[package-list.txt](https://github.com/rikuu/Gap2Seq/files/6595670/package-list.txt)

Merging filled gaps and contigs
Traceback (most recent call last):
  File "/home/mgl111/miniconda3/envs/gap2seqEnv/bin/Gap2Seq", line 505, in <module>
    merge_gaps(args['filled'], args['final_out'])
  File "/home/mgl111/miniconda3/envs/gap2seqEnv/bin/Gap2Seq", line 319, in merge_gaps
    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/home/mgl111/miniconda3/envs/gap2seqEnv/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/mgl111/miniconda3/envs/gap2seqEnv/bin/GapMerger', '-scaffolds', 'Assembly/SGA/genome.scf.fill.fasta', '-gaps', 'tmp.filled', '-contigs', 'tmp.contigs']' returned non-zero exit status 1.
